---
- name: reload firewall
  service: name=iptables state=restarted
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'

- name: reload firewall
  command: firewall-cmd --reload
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

- name: restart tomcat 
  service: name={{tc_instance_name}} state=restarted
