---
- name: Copy MongoDB repo definiton
  copy: src=mongodb.repo dest=/etc/yum.repos.d

- name: Install MongoDB
  yum: name=mongodb-org state=present

- name: Save default mongod.conf file
  command: cp /etc/mongod.conf /etc/mongod.conf.default creates=/etc/mongod.conf.default 

- name: Allow MongoDB to listen for all connections
  lineinfile: dest=/etc/mongod.conf regexp='bindIp' state=absent

- name: Start MongoDB
  service: name=mongod state=started

- name: deploy firewall rule
  command: iptables -I INPUT -p tcp -m tcp --dport 27017 -j ACCEPT
  notify: reload firewall
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'

- name: save firewall rule
  command: service iptables save
  notify: reload firewall
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'

- name: deploy firewall rule
  command: firewall-cmd --zone=public --add-port=27017/tcp --permanent
  notify: reload firewall
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'
