---
- name: Install EPEL on CentOS
  yum: name=epel-release state=installed
  when: ansible_distribution == 'CentOS'

- name: Download EPEL on RHEL
  get_url: url=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm dest=/tmp
  when: ansible_distribution == 'RedHat'

- name: Install EPEL on RHEL
  yum: name=/tmp/epel-release-latest-7.noarch.rpm state=present
  when: ansible_distribution == 'RedHat'

- name: Install the libselinux-python package
  yum: name=libselinux-python state=installed
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'

- name: Install git
  yum: name=git-all state=present
