---
- name: Copy MongoDB repo definiton
  copy: src=mongodb.repo dest=/etc/yum.repos.d

- name: Install MongoDB
  yum: name={{item}} state=present
  with_items:
    - mongodb-org-shell
    - mongodb-org-tools

